from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.common import TimestampMixin


class Subscription(Base, TimestampMixin):
    """Company subscription — one per company."""
    __tablename__ = "subscriptions"

    id: Mapped[int] = mapped_column(primary_key=True)
    company_id: Mapped[int] = mapped_column(Integer, ForeignKey("companies.id"), unique=True, index=True)
    plan: Mapped[str] = mapped_column(String(50), default="trial")  # trial, starter, professional, enterprise
    status: Mapped[str] = mapped_column(String(20), default="active")  # active, expired, suspended
    starts_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    max_users: Mapped[int] = mapped_column(Integer, default=5)
    max_devices: Mapped[int] = mapped_column(Integer, default=2)
    max_invoices_per_month: Mapped[int] = mapped_column(Integer, default=100)
    notes: Mapped[str] = mapped_column(Text, default="")

    company = relationship("Company", back_populates="subscription")


class ActivationCode(Base, TimestampMixin):
    """Activation code generated by admin for a portal user to activate their company subscription."""
    __tablename__ = "activation_codes"

    id: Mapped[int] = mapped_column(primary_key=True)
    code: Mapped[str] = mapped_column(String(20), unique=True, index=True)
    company_id: Mapped[int] = mapped_column(Integer, ForeignKey("companies.id"), index=True)
    plan: Mapped[str] = mapped_column(String(50), default="starter")
    duration_days: Mapped[int] = mapped_column(Integer, default=365)
    max_users: Mapped[int] = mapped_column(Integer, default=5)
    max_devices: Mapped[int] = mapped_column(Integer, default=2)
    max_invoices_per_month: Mapped[int] = mapped_column(Integer, default=500)
    is_used: Mapped[bool] = mapped_column(Boolean, default=False)
    used_by_user_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("users.id"), nullable=True)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    company = relationship("Company")
    used_by = relationship("User")
