"""tax_settings_and_certificates

Revision ID: 235b5e8194a7
Revises: e6bc0f216b36
Create Date: 2026-02-03 11:53:40.069425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235b5e8194a7'
down_revision: Union[str, None] = 'e6bc0f216b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('crt_filename', sa.String(length=255), nullable=False),
    sa.Column('crt_data', sa.LargeBinary(), nullable=True),
    sa.Column('key_filename', sa.String(length=255), nullable=False),
    sa.Column('key_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_certificates_company_id'), 'company_certificates', ['company_id'], unique=False)
    op.create_table('tax_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('zimra_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_settings_company_id'), 'tax_settings', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_settings_company_id'), table_name='tax_settings')
    op.drop_table('tax_settings')
    op.drop_index(op.f('ix_company_certificates_company_id'), table_name='company_certificates')
    op.drop_table('company_certificates')
    # ### end Alembic commands ###